apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
      origin: fabien
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
        origin: fabien
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80