version: '3.7'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: laravel_php_app
    working_dir: /var/www
    container_name: "laravel_php"
    networks:
      - app-network
    volumes:
      - ./www:/var/www
    depends_on:
      - mariadb
  nginx:
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8080:80
    container_name: "laravel_nginx"
    networks:
      - app-network
    depends_on:
      - php
      - mariadb
  mariadb:
    image: mariadb:10.4
    container_name: "laravel_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - app-network
networks:
  app-network:
    driver: bridge